version: '3'

services:

  chromecast:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    command: catt --device ${CHROMECAST_IP} cast_site '${CAST_URL}'
    #command: catt scan