version: '3'

services:

  chromecast:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: bridge
    command: catt --device 'Office Dashboard' cast_site 'https://redleg.app'