version: '3'

services:

  chromecast:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    command: catt --device ${CHROMECAST_IP} cast_site '${CAST_URL}'
    #command: catt scan
    
    # Catt seems to time out periodically, and benefits from just restarting the container
  restarter:
    image: docker
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 2h; docker restart chromecast-chromecast-1; done" ]
    restart: unless-stopped