version: '3'

services:

  chromecast:
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    command: catt --device 192.168.86.45 cast_site 'https://dakboard.com/display/uuid/632dc0ca-123142-bc2f-27fff209'
    #command: catt scan