version: "3"

services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
    # Changed from default
      - "8008:80"
      - "8009:443"
    volumes:
      - ./data:/appsmith-stacks
    restart: unless-stopped
    # Uncomment the lines below to enable auto-update
    labels:
      com.centurylinklabs.watchtower.enable: "true"