version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BASEROW_PUBLIC_URL=${BASEROW_PUBLIC_URL}
    ports:
      - "4443:443"
      - "8082:80"
    volumes:
      - ./data:/baserow/data
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'