version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.mattgwagner.com'
    ports:
      - "4443:443"
    volumes:
      - ./data:/baserow/data