version: '3.5'

services:

  seq.logging:
    image: datalust/seq:latest
    container_name: seq.logging
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./data:/data
    ports:
      - "8081:80" # UI
