version: '3.5'

services:

  seq.logging:
    image: datalust/seq:2021.1
    container_name: seq.logging
    environment:
      - ACCEPT_EULA=Y
    volumes:
        # Data is the name of my Azure storage mount
      - Data:/data
    ports:
      - "80:80" # UI
