version: "3.8"

services:
  grist:
    image: gristlabs/grist:latest
    ports:
      - "8484:443"
    environment:
      - PORT=443
    volumes:
      - ./data:/persist
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'