version: "3"
services:
  android:
    image: budtmo/docker-android:emulator_13.0
    ports:
      - "6080:6080"
      - 9000
    volumes:
      - ./data:/data
    environment:
      - EMULATOR_DEVICE="Samsung Galaxy S10"
      - WEB_VNC=true
      - WEB_LOG=true
      - WEB_LOG_PORT=9000