version: "3"

services:

# Add these labels to a container definition
    # Uncomment the lines below to enable auto-update
    #labels:
      #com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
    environment:
      - WATCHTOWER_LIFECYCLE_HOOKS=true