version: "3"

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: ${SQL_SA_PASSWORD}
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"