version: "3"

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: ${SQL_SA_PASSWORD}
            ACCEPT_EULA: "Y"
            MSQL_PID: Developer
        ports:
            - "1433:1433"
        volumes:
            - mssql-data:/var/opt/mssql/data

volumes:
    mssql-data: