services:
  minecraft-4:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25568:25565"
    volumes:
      - ./data-4:/data
    environment:
      EULA: "TRUE"
      MOTD: Welcome to Wagnerland 4, powered by Red Leg Dev
    restart: unless-stopped
  minecraft-5:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data-5:/data
    environment:
      EULA: "TRUE"
    restart: unless-stopped