services:
  minecraft:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      MOTD: Welcome to Wagnerland, powered by Red Leg Dev
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
    restart: unless-stopped