services:
    
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: